# SPDX-FileCopyrightText: 2014, 2016 CERN.
# SPDX-License-Identifier: BSD-3-Clause


[pytest]
addopts = --isort --pydocstyle --pycodestyle --doctest-glob="*.rst" --doctest-modules --cov=dojson --cov-report=term-missing
testpaths = tests dojson
filterwarnings = ignore::pytest.PytestDeprecationWarning
