# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2020 CERN.
# Copyright (C) 2023 Graz University of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel babel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          # The token is provided by the inveniosoftware organization
          password: ${{ secrets.pypi_token }}
